### ISSUE TITLE
Automatic horizontal Pod scaling of drupal8 service

### ISSUE THREAD

**Issue by geerlingguy** [geerlingguy/raspberry-pi-dramble#105]
As the title says... I would like to set up automatic horizontal pod scaling for the `drupal8` service, so that when CPU or RAM usage is above 50% for more than 3 minutes, another pod/replica is added.

**Comment by geerlingguy** [comment]
Looks like I also need to deploy [`metrics-server`](https://github.com/kubernetes-incubator/metrics-server) (which is not included OOTB) so the HPA (Horizontal Pod Autoscaler) can get the metrics it needs to be able to determine when it should scale up or scale down.

Other than that, adding an HPA is pretty simple:

```yaml
---
# Definition of Drupal 8 Horizontal Pod Autoscaler.
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: drupal8
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: drupal8
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50
```

But currently without `metrics-server` in place, I'm getting:

```
root@kube1:~# kubectl describe hpa drupal8
Name:                                                  drupal8
Namespace:                                             default
Labels:                                                <none>
Annotations:                                           kubectl.kubernetes.io/last-applied-configuration={"apiVersion":"autoscaling/v1","kind":"HorizontalPodAutoscaler","metadata":{"annotations":{},"name":"drupal8","namespace":"default"},"spec":{"maxReplic...
CreationTimestamp:                                     Sat, 28 Jul 2018 02:40:16 +0000
Reference:                                             Deployment/drupal8
Metrics:                                               ( current / target )
  resource cpu on pods  (as a percentage of request):  <unknown> / 50%
Min replicas:                                          1
Max replicas:                                          10
Deployment pods:                                       1 current / 0 desired
Conditions:
  Type           Status  Reason                   Message
  ----           ------  ------                   -------
  AbleToScale    True    SucceededGetScale        the HPA controller was able to get the target's current scale
  ScalingActive  False   FailedGetResourceMetric  the HPA was unable to compute the replica count: unable to get metrics for resource cpu: unable to fetch metrics from resource metrics API: the server could not find the requested resource (get pods.metrics.k8s.io)
Events:
  Type     Reason                        Age               From                       Message
  ----     ------                        ----              ----                       -------
  Warning  FailedGetResourceMetric       14s (x8 over 3m)  horizontal-pod-autoscaler  unable to get metrics for resource cpu: unable to fetch metrics from resource metrics API: the server could not find the requested resource (get pods.metrics.k8s.io)
  Warning  FailedComputeMetricsReplicas  14s (x8 over 3m)  horizontal-pod-autoscaler  failed to get cpu utilization: unable to get metrics for resource cpu: unable to fetch metrics from resource metrics API: the server could not find the requested resource (get pods.metrics.k8s.io)
```

**Comment by geerlingguy** [comment]
`metrics-server` quick install:

    git clone https://github.com/kubernetes-incubator/metrics-server.git
    cd metrics-server/
    kubectl create -f deploy/1.8+/

**Comment by geerlingguy** [comment]
The Drupal 8 `Deployment` also had to be updated to have a specific cpu `request` for resources, so the HPA has a reference for what '50%' CPU usage is:

```yaml
    spec:
      containers:
        - image: geerlingguy/drupal:latest
          imagePullPolicy: Always
          ...
          resources:
            requests:
              cpu: 500m
```
