### ISSUE TITLE
Create an NFS mount for the drupal8 files directory

### ISSUE THREAD

**Issue by geerlingguy** [geerlingguy/raspberry-pi-dramble#110]
To do this:

  1. Create a directory inside `/mnt/nfs` like `/mnt/nfs/drupal8-files`
  2. Create an NFS PV, e.g.:

```yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: drupal8-nfs-pv 
spec:
  capacity:
    storage: 8Gi 
  accessModes:
    - ReadWriteMany 
  persistentVolumeReclaimPolicy: Retain 
  nfs: 
    path: /opt/nfs 
    server: kube1 
    readOnly: false
```

  3. Create an NFS PVC, e.g.:

```yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: drupal8-nfs-pvc  
spec:
  accessModes:
  - ReadWriteMany      
  resources:
     requests:
       storage: 8Gi 
```

  4. In the Drupal container configuration:

```yaml
apiVersion: v1
kind: Pod
metadata:
  ...
spec:
  containers:
    - name: ...
      image: ...
      ports: ...
      volumeMounts:
        - name: drupal8-files
          mountPath: /var/www/html/sites/default/files
  volumes:
    - name: drupal8-files
      persistentVolumeClaim:
        claimName: drupal8-nfs-pvc
```

Adapted from [Sharing an NFS Persistent Volume (PV) Across Two Pods](https://docs.openshift.org/latest/install_config/storage_examples/shared_storage.html).
