### ISSUE TITLE
Configure Nginx selective cache purging with Purge + Expire?

### ISSUE THREAD

**Issue by geerlingguy** [geerlingguy/raspberry-pi-dramble#19]
Are there modules for D8 yet?

Looks like we have:

  - [Purge](https://www.drupal.org/project/purge) has an 8.x branch
  - [Cache Expiration](https://www.drupal.org/project/expire) has an [issue for a D8 roadmap](https://www.drupal.org/node/2137315) with zero activity so far :(

Any other methods of proactively purging things? Or will I need to dump the `/var/cache/nginx/*` directory every time I deploy an update? (Or set the max page TTL way lower under `/admin/config/development/performance`).

**Comment by geerlingguy** [comment]
I think it will be adequate to simply run the command `rm -rf /var/cache/nginx/*`, delegated to the balancer... something like a new handler:

```yaml
    - name: purge nginx cache
      shell: "rm -rf /var/cache/nginx/*"
      delegate_to: "{{ item }}"
      with_items: groups.balancer
```

Then call that handler from the main playbook.
