### ISSUE TITLE
Make sure MySQL replication is configured

### ISSUE THREAD

**Issue by geerlingguy** [geerlingguy/raspberry-pi-dramble#70]
Currently it's not; probably just some tiny change I forgot to make when adapting the infrastructure architecture...

**Comment by geerlingguy** [comment]
```yaml
mysql_databases:
  - {
    name: drupal,
    collation: utf8_general_ci,
    encoding: utf8,
    replicate: 0
  }
```

Yep. Let's try `replicate: 1` :)
